### ISSUE TITLE
Add go-task

### ISSUE THREAD

**Issue by jmdots** [cisco-sso/kdk#104]
https://github.com/go-task/task/releases

To demonstrate this tool works, here is very basic example `Taskfile.yml`:

```
version: "2"

tasks:

  default:
    cmds:
      - task: install

  install:
    desc: Install to Kubernetes.
    deps:
      - tiller
      - nginx-ingress
      - consul

  tiller:
    desc: Install Helm Tiller.
    cmds:
      - helm init --wait

  nginx-ingress:
    desc: Install Helm Chart for Nginx Ingress.
    cmds:
      - helm upgrade --install --recreate-pods
          --namespace nginx-ingress
          --values nginx-ingress/values.yaml
          nginx-ingress stable/nginx-ingress

  consul:
    desc: Install Helm Chart for Consul.
    cmds:
      - helm upgrade --install --recreate-pods
          --namespace consul
          --values consul/values.yaml
          consul stable/consul
```
