### ISSUE TITLE
Allow common parameters to kdk to be passed as a string or from a file

### ISSUE THREAD

**Issue by rtluckie** [cisco-sso/kdk#98]
I destroy and recreate kdk containers quite often.  It would be nice if we could allow the users to pass in the configuration as a string or from a file and avoid the interactive prompts alltogether.

something like this...

```bash
kdk init --config '{"Name": "kdk0", "DotfilesRepo": "https://github.com/rtluckie/work-dotfiles.git", "Shell": "/usr/local/bin/zsh", "KeybaseMount": true, "ExtraMounts": [{"Source": "/User/jdoe/projects", "Target": "/home/jdoe/projects"}, {"Source": "/User/jdoe/docs", "Target": "/home/jdoe/docs"}], "socks": {"enable": true, "port": 8000}}'
```

```bash
kdk init --config-from-file my-kdk-config.yaml
```

```yaml
# my-kdk-config.yaml
Name: kdk0
DotfilesRepo: https://github.com/rtluckie/work-dotfiles.git
Dhell: "/usr/local/bin/zsh"
DeybaseMount: true
ExtraMounts:
- Source: "/User/jdoe/projects"
  Target: "/home/jdoe/projects"
- Source: "/User/jdoe/docs"
  Target: "/home/jdoe/docs"
Socks:
  enable: true
  port: 8000
```

We also may want to consider enabling the user to override elements of `ContainerConfig` or `HostConfig`, but that would take some more thought.
